services:
  web:
    image: webdevops/php-apache:alpine-php7
    ports:
      - '8090:80'
    volumes:
      - ./web:/app
    networks:
      - geral
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: admin
    networks:
      - geral
    expose:
      - 3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: admin
    networks:
      - geral

networks:
  geral: